//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4screen.CSB.WebUI.UserControls
{


    public partial class GoogleMap
    {
        protected global::System.Web.UI.WebControls.Panel PnlNavi;
        protected global::System.Web.UI.WebControls.Panel PnlMap;
        protected global::System.Web.UI.WebControls.Literal LitScript;
        protected global::System.Web.UI.WebControls.Literal LitMap;
        protected global::Telerik.Web.UI.RadTreeView Rtv;
    }
}
