//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://localhost/")]
public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private AuthenticationHeader authenticationHeaderValueField;
    
    private System.Threading.SendOrPostCallback AuthenticateOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetUsersOperationCompleted;
    
    private System.Threading.SendOrPostCallback LockUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback UnlockUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback SetUserEmailOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetDataObjectsOperationCompleted;
    
    private System.Threading.SendOrPostCallback FeatureDataObjectOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetContentDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback SetContentDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetAdCampaignsOperationCompleted;
    
    private System.Threading.SendOrPostCallback SaveAdCampaignOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetAdWordsOperationCompleted;
    
    private System.Threading.SendOrPostCallback SaveAdWordOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetObjectCountPerTypeOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetObjectCountPerTypeTodayOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetObjectViewCountPerTypeOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetObjectViewCountPerTypeTodayOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetInterestInArtCountOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetInterestInPoliticsCountOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetInterestInLifestyleCountOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetInterestInCareerCountOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetUserTagWordCountOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetTopEmailProviderOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetTopHomeRegionOperationCompleted;
    
    /// <remarks/>
    public Service() {
        this.Url = "http://localhost:51272/Service.asmx";
    }
    
    public AuthenticationHeader AuthenticationHeaderValue {
        get {
            return this.authenticationHeaderValueField;
        }
        set {
            this.authenticationHeaderValueField = value;
        }
    }
    
    /// <remarks/>
    public event AuthenticateCompletedEventHandler AuthenticateCompleted;
    
    /// <remarks/>
    public event GetUsersCompletedEventHandler GetUsersCompleted;
    
    /// <remarks/>
    public event LockUserCompletedEventHandler LockUserCompleted;
    
    /// <remarks/>
    public event UnlockUserCompletedEventHandler UnlockUserCompleted;
    
    /// <remarks/>
    public event SetUserEmailCompletedEventHandler SetUserEmailCompleted;
    
    /// <remarks/>
    public event GetDataObjectsCompletedEventHandler GetDataObjectsCompleted;
    
    /// <remarks/>
    public event FeatureDataObjectCompletedEventHandler FeatureDataObjectCompleted;
    
    /// <remarks/>
    public event GetContentDataCompletedEventHandler GetContentDataCompleted;
    
    /// <remarks/>
    public event SetContentDataCompletedEventHandler SetContentDataCompleted;
    
    /// <remarks/>
    public event GetAdCampaignsCompletedEventHandler GetAdCampaignsCompleted;
    
    /// <remarks/>
    public event SaveAdCampaignCompletedEventHandler SaveAdCampaignCompleted;
    
    /// <remarks/>
    public event GetAdWordsCompletedEventHandler GetAdWordsCompleted;
    
    /// <remarks/>
    public event SaveAdWordCompletedEventHandler SaveAdWordCompleted;
    
    /// <remarks/>
    public event GetObjectCountPerTypeCompletedEventHandler GetObjectCountPerTypeCompleted;
    
    /// <remarks/>
    public event GetObjectCountPerTypeTodayCompletedEventHandler GetObjectCountPerTypeTodayCompleted;
    
    /// <remarks/>
    public event GetObjectViewCountPerTypeCompletedEventHandler GetObjectViewCountPerTypeCompleted;
    
    /// <remarks/>
    public event GetObjectViewCountPerTypeTodayCompletedEventHandler GetObjectViewCountPerTypeTodayCompleted;
    
    /// <remarks/>
    public event GetInterestInArtCountCompletedEventHandler GetInterestInArtCountCompleted;
    
    /// <remarks/>
    public event GetInterestInPoliticsCountCompletedEventHandler GetInterestInPoliticsCountCompleted;
    
    /// <remarks/>
    public event GetInterestInLifestyleCountCompletedEventHandler GetInterestInLifestyleCountCompleted;
    
    /// <remarks/>
    public event GetInterestInCareerCountCompletedEventHandler GetInterestInCareerCountCompleted;
    
    /// <remarks/>
    public event GetUserTagWordCountCompletedEventHandler GetUserTagWordCountCompleted;
    
    /// <remarks/>
    public event GetTopEmailProviderCompletedEventHandler GetTopEmailProviderCompleted;
    
    /// <remarks/>
    public event GetTopHomeRegionCompletedEventHandler GetTopHomeRegionCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/Authenticate", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Authorization Authenticate() {
        object[] results = this.Invoke("Authenticate", new object[0]);
        return ((Authorization)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAuthenticate(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Authenticate", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public Authorization EndAuthenticate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Authorization)(results[0]));
    }
    
    /// <remarks/>
    public void AuthenticateAsync() {
        this.AuthenticateAsync(null);
    }
    
    /// <remarks/>
    public void AuthenticateAsync(object userState) {
        if ((this.AuthenticateOperationCompleted == null)) {
            this.AuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateOperationCompleted);
        }
        this.InvokeAsync("Authenticate", new object[0], this.AuthenticateOperationCompleted, userState);
    }
    
    private void OnAuthenticateOperationCompleted(object arg) {
        if ((this.AuthenticateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GetUsers", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public User[] GetUsers(string username, string email, bool isLocked) {
        object[] results = this.Invoke("GetUsers", new object[] {
                    username,
                    email,
                    isLocked});
        return ((User[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetUsers(string username, string email, bool isLocked, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetUsers", new object[] {
                    username,
                    email,
                    isLocked}, callback, asyncState);
    }
    
    /// <remarks/>
    public User[] EndGetUsers(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((User[])(results[0]));
    }
    
    /// <remarks/>
    public void GetUsersAsync(string username, string email, bool isLocked) {
        this.GetUsersAsync(username, email, isLocked, null);
    }
    
    /// <remarks/>
    public void GetUsersAsync(string username, string email, bool isLocked, object userState) {
        if ((this.GetUsersOperationCompleted == null)) {
            this.GetUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersOperationCompleted);
        }
        this.InvokeAsync("GetUsers", new object[] {
                    username,
                    email,
                    isLocked}, this.GetUsersOperationCompleted, userState);
    }
    
    private void OnGetUsersOperationCompleted(object arg) {
        if ((this.GetUsersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetUsersCompleted(this, new GetUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/LockUser", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool LockUser(string username) {
        object[] results = this.Invoke("LockUser", new object[] {
                    username});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLockUser(string username, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("LockUser", new object[] {
                    username}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndLockUser(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void LockUserAsync(string username) {
        this.LockUserAsync(username, null);
    }
    
    /// <remarks/>
    public void LockUserAsync(string username, object userState) {
        if ((this.LockUserOperationCompleted == null)) {
            this.LockUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLockUserOperationCompleted);
        }
        this.InvokeAsync("LockUser", new object[] {
                    username}, this.LockUserOperationCompleted, userState);
    }
    
    private void OnLockUserOperationCompleted(object arg) {
        if ((this.LockUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LockUserCompleted(this, new LockUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/UnlockUser", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool UnlockUser(string username) {
        object[] results = this.Invoke("UnlockUser", new object[] {
                    username});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUnlockUser(string username, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UnlockUser", new object[] {
                    username}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndUnlockUser(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void UnlockUserAsync(string username) {
        this.UnlockUserAsync(username, null);
    }
    
    /// <remarks/>
    public void UnlockUserAsync(string username, object userState) {
        if ((this.UnlockUserOperationCompleted == null)) {
            this.UnlockUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnlockUserOperationCompleted);
        }
        this.InvokeAsync("UnlockUser", new object[] {
                    username}, this.UnlockUserOperationCompleted, userState);
    }
    
    private void OnUnlockUserOperationCompleted(object arg) {
        if ((this.UnlockUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UnlockUserCompleted(this, new UnlockUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/SetUserEmail", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool SetUserEmail(string username, string email) {
        object[] results = this.Invoke("SetUserEmail", new object[] {
                    username,
                    email});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSetUserEmail(string username, string email, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SetUserEmail", new object[] {
                    username,
                    email}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndSetUserEmail(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void SetUserEmailAsync(string username, string email) {
        this.SetUserEmailAsync(username, email, null);
    }
    
    /// <remarks/>
    public void SetUserEmailAsync(string username, string email, object userState) {
        if ((this.SetUserEmailOperationCompleted == null)) {
            this.SetUserEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetUserEmailOperationCompleted);
        }
        this.InvokeAsync("SetUserEmail", new object[] {
                    username,
                    email}, this.SetUserEmailOperationCompleted, userState);
    }
    
    private void OnSetUserEmailOperationCompleted(object arg) {
        if ((this.SetUserEmailCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SetUserEmailCompleted(this, new SetUserEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GetDataObjects", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public CSBDataObject[] GetDataObjects(string objectId, string communityId, string userId, bool featured) {
        object[] results = this.Invoke("GetDataObjects", new object[] {
                    objectId,
                    communityId,
                    userId,
                    featured});
        return ((CSBDataObject[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetDataObjects(string objectId, string communityId, string userId, bool featured, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetDataObjects", new object[] {
                    objectId,
                    communityId,
                    userId,
                    featured}, callback, asyncState);
    }
    
    /// <remarks/>
    public CSBDataObject[] EndGetDataObjects(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CSBDataObject[])(results[0]));
    }
    
    /// <remarks/>
    public void GetDataObjectsAsync(string objectId, string communityId, string userId, bool featured) {
        this.GetDataObjectsAsync(objectId, communityId, userId, featured, null);
    }
    
    /// <remarks/>
    public void GetDataObjectsAsync(string objectId, string communityId, string userId, bool featured, object userState) {
        if ((this.GetDataObjectsOperationCompleted == null)) {
            this.GetDataObjectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataObjectsOperationCompleted);
        }
        this.InvokeAsync("GetDataObjects", new object[] {
                    objectId,
                    communityId,
                    userId,
                    featured}, this.GetDataObjectsOperationCompleted, userState);
    }
    
    private void OnGetDataObjectsOperationCompleted(object arg) {
        if ((this.GetDataObjectsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDataObjectsCompleted(this, new GetDataObjectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/FeatureDataObject", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool FeatureDataObject(string objectId, bool featured) {
        object[] results = this.Invoke("FeatureDataObject", new object[] {
                    objectId,
                    featured});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginFeatureDataObject(string objectId, bool featured, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("FeatureDataObject", new object[] {
                    objectId,
                    featured}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndFeatureDataObject(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void FeatureDataObjectAsync(string objectId, bool featured) {
        this.FeatureDataObjectAsync(objectId, featured, null);
    }
    
    /// <remarks/>
    public void FeatureDataObjectAsync(string objectId, bool featured, object userState) {
        if ((this.FeatureDataObjectOperationCompleted == null)) {
            this.FeatureDataObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFeatureDataObjectOperationCompleted);
        }
        this.InvokeAsync("FeatureDataObject", new object[] {
                    objectId,
                    featured}, this.FeatureDataObjectOperationCompleted, userState);
    }
    
    private void OnFeatureDataObjectOperationCompleted(object arg) {
        if ((this.FeatureDataObjectCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.FeatureDataObjectCompleted(this, new FeatureDataObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GetContentData", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ContentData[] GetContentData() {
        object[] results = this.Invoke("GetContentData", new object[0]);
        return ((ContentData[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetContentData(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetContentData", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ContentData[] EndGetContentData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ContentData[])(results[0]));
    }
    
    /// <remarks/>
    public void GetContentDataAsync() {
        this.GetContentDataAsync(null);
    }
    
    /// <remarks/>
    public void GetContentDataAsync(object userState) {
        if ((this.GetContentDataOperationCompleted == null)) {
            this.GetContentDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContentDataOperationCompleted);
        }
        this.InvokeAsync("GetContentData", new object[0], this.GetContentDataOperationCompleted, userState);
    }
    
    private void OnGetContentDataOperationCompleted(object arg) {
        if ((this.GetContentDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetContentDataCompleted(this, new GetContentDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/SetContentData", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool SetContentData(string key, string content) {
        object[] results = this.Invoke("SetContentData", new object[] {
                    key,
                    content});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSetContentData(string key, string content, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SetContentData", new object[] {
                    key,
                    content}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndSetContentData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void SetContentDataAsync(string key, string content) {
        this.SetContentDataAsync(key, content, null);
    }
    
    /// <remarks/>
    public void SetContentDataAsync(string key, string content, object userState) {
        if ((this.SetContentDataOperationCompleted == null)) {
            this.SetContentDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetContentDataOperationCompleted);
        }
        this.InvokeAsync("SetContentData", new object[] {
                    key,
                    content}, this.SetContentDataOperationCompleted, userState);
    }
    
    private void OnSetContentDataOperationCompleted(object arg) {
        if ((this.SetContentDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SetContentDataCompleted(this, new SetContentDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GetAdCampaigns", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public CSBAdCampaign[] GetAdCampaigns() {
        object[] results = this.Invoke("GetAdCampaigns", new object[0]);
        return ((CSBAdCampaign[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetAdCampaigns(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetAdCampaigns", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public CSBAdCampaign[] EndGetAdCampaigns(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CSBAdCampaign[])(results[0]));
    }
    
    /// <remarks/>
    public void GetAdCampaignsAsync() {
        this.GetAdCampaignsAsync(null);
    }
    
    /// <remarks/>
    public void GetAdCampaignsAsync(object userState) {
        if ((this.GetAdCampaignsOperationCompleted == null)) {
            this.GetAdCampaignsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAdCampaignsOperationCompleted);
        }
        this.InvokeAsync("GetAdCampaigns", new object[0], this.GetAdCampaignsOperationCompleted, userState);
    }
    
    private void OnGetAdCampaignsOperationCompleted(object arg) {
        if ((this.GetAdCampaignsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetAdCampaignsCompleted(this, new GetAdCampaignsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/SaveAdCampaign", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool SaveAdCampaign(CSBAdCampaign adCampaign) {
        object[] results = this.Invoke("SaveAdCampaign", new object[] {
                    adCampaign});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSaveAdCampaign(CSBAdCampaign adCampaign, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SaveAdCampaign", new object[] {
                    adCampaign}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndSaveAdCampaign(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void SaveAdCampaignAsync(CSBAdCampaign adCampaign) {
        this.SaveAdCampaignAsync(adCampaign, null);
    }
    
    /// <remarks/>
    public void SaveAdCampaignAsync(CSBAdCampaign adCampaign, object userState) {
        if ((this.SaveAdCampaignOperationCompleted == null)) {
            this.SaveAdCampaignOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveAdCampaignOperationCompleted);
        }
        this.InvokeAsync("SaveAdCampaign", new object[] {
                    adCampaign}, this.SaveAdCampaignOperationCompleted, userState);
    }
    
    private void OnSaveAdCampaignOperationCompleted(object arg) {
        if ((this.SaveAdCampaignCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SaveAdCampaignCompleted(this, new SaveAdCampaignCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GetAdWords", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public CSBAdWord[] GetAdWords() {
        object[] results = this.Invoke("GetAdWords", new object[0]);
        return ((CSBAdWord[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetAdWords(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetAdWords", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public CSBAdWord[] EndGetAdWords(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((CSBAdWord[])(results[0]));
    }
    
    /// <remarks/>
    public void GetAdWordsAsync() {
        this.GetAdWordsAsync(null);
    }
    
    /// <remarks/>
    public void GetAdWordsAsync(object userState) {
        if ((this.GetAdWordsOperationCompleted == null)) {
            this.GetAdWordsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAdWordsOperationCompleted);
        }
        this.InvokeAsync("GetAdWords", new object[0], this.GetAdWordsOperationCompleted, userState);
    }
    
    private void OnGetAdWordsOperationCompleted(object arg) {
        if ((this.GetAdWordsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetAdWordsCompleted(this, new GetAdWordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/SaveAdWord", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool SaveAdWord(CSBAdWord adWord) {
        object[] results = this.Invoke("SaveAdWord", new object[] {
                    adWord});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSaveAdWord(CSBAdWord adWord, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SaveAdWord", new object[] {
                    adWord}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndSaveAdWord(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void SaveAdWordAsync(CSBAdWord adWord) {
        this.SaveAdWordAsync(adWord, null);
    }
    
    /// <remarks/>
    public void SaveAdWordAsync(CSBAdWord adWord, object userState) {
        if ((this.SaveAdWordOperationCompleted == null)) {
            this.SaveAdWordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveAdWordOperationCompleted);
        }
        this.InvokeAsync("SaveAdWord", new object[] {
                    adWord}, this.SaveAdWordOperationCompleted, userState);
    }
    
    private void OnSaveAdWordOperationCompleted(object arg) {
        if ((this.SaveAdWordCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SaveAdWordCompleted(this, new SaveAdWordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GetObjectCountPerType", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ChartDataPair[] GetObjectCountPerType() {
        object[] results = this.Invoke("GetObjectCountPerType", new object[0]);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetObjectCountPerType(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetObjectCountPerType", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ChartDataPair[] EndGetObjectCountPerType(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public void GetObjectCountPerTypeAsync() {
        this.GetObjectCountPerTypeAsync(null);
    }
    
    /// <remarks/>
    public void GetObjectCountPerTypeAsync(object userState) {
        if ((this.GetObjectCountPerTypeOperationCompleted == null)) {
            this.GetObjectCountPerTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetObjectCountPerTypeOperationCompleted);
        }
        this.InvokeAsync("GetObjectCountPerType", new object[0], this.GetObjectCountPerTypeOperationCompleted, userState);
    }
    
    private void OnGetObjectCountPerTypeOperationCompleted(object arg) {
        if ((this.GetObjectCountPerTypeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetObjectCountPerTypeCompleted(this, new GetObjectCountPerTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GetObjectCountPerTypeToday", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ChartDataPair[] GetObjectCountPerTypeToday() {
        object[] results = this.Invoke("GetObjectCountPerTypeToday", new object[0]);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetObjectCountPerTypeToday(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetObjectCountPerTypeToday", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ChartDataPair[] EndGetObjectCountPerTypeToday(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public void GetObjectCountPerTypeTodayAsync() {
        this.GetObjectCountPerTypeTodayAsync(null);
    }
    
    /// <remarks/>
    public void GetObjectCountPerTypeTodayAsync(object userState) {
        if ((this.GetObjectCountPerTypeTodayOperationCompleted == null)) {
            this.GetObjectCountPerTypeTodayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetObjectCountPerTypeTodayOperationCompleted);
        }
        this.InvokeAsync("GetObjectCountPerTypeToday", new object[0], this.GetObjectCountPerTypeTodayOperationCompleted, userState);
    }
    
    private void OnGetObjectCountPerTypeTodayOperationCompleted(object arg) {
        if ((this.GetObjectCountPerTypeTodayCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetObjectCountPerTypeTodayCompleted(this, new GetObjectCountPerTypeTodayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GetObjectViewCountPerType", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ChartDataPair[] GetObjectViewCountPerType() {
        object[] results = this.Invoke("GetObjectViewCountPerType", new object[0]);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetObjectViewCountPerType(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetObjectViewCountPerType", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ChartDataPair[] EndGetObjectViewCountPerType(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public void GetObjectViewCountPerTypeAsync() {
        this.GetObjectViewCountPerTypeAsync(null);
    }
    
    /// <remarks/>
    public void GetObjectViewCountPerTypeAsync(object userState) {
        if ((this.GetObjectViewCountPerTypeOperationCompleted == null)) {
            this.GetObjectViewCountPerTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetObjectViewCountPerTypeOperationCompleted);
        }
        this.InvokeAsync("GetObjectViewCountPerType", new object[0], this.GetObjectViewCountPerTypeOperationCompleted, userState);
    }
    
    private void OnGetObjectViewCountPerTypeOperationCompleted(object arg) {
        if ((this.GetObjectViewCountPerTypeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetObjectViewCountPerTypeCompleted(this, new GetObjectViewCountPerTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GetObjectViewCountPerTypeToday", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ChartDataPair[] GetObjectViewCountPerTypeToday() {
        object[] results = this.Invoke("GetObjectViewCountPerTypeToday", new object[0]);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetObjectViewCountPerTypeToday(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetObjectViewCountPerTypeToday", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ChartDataPair[] EndGetObjectViewCountPerTypeToday(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public void GetObjectViewCountPerTypeTodayAsync() {
        this.GetObjectViewCountPerTypeTodayAsync(null);
    }
    
    /// <remarks/>
    public void GetObjectViewCountPerTypeTodayAsync(object userState) {
        if ((this.GetObjectViewCountPerTypeTodayOperationCompleted == null)) {
            this.GetObjectViewCountPerTypeTodayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetObjectViewCountPerTypeTodayOperationCompleted);
        }
        this.InvokeAsync("GetObjectViewCountPerTypeToday", new object[0], this.GetObjectViewCountPerTypeTodayOperationCompleted, userState);
    }
    
    private void OnGetObjectViewCountPerTypeTodayOperationCompleted(object arg) {
        if ((this.GetObjectViewCountPerTypeTodayCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetObjectViewCountPerTypeTodayCompleted(this, new GetObjectViewCountPerTypeTodayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GetInterestInArtCount", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ChartDataPair[] GetInterestInArtCount() {
        object[] results = this.Invoke("GetInterestInArtCount", new object[0]);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetInterestInArtCount(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetInterestInArtCount", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ChartDataPair[] EndGetInterestInArtCount(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public void GetInterestInArtCountAsync() {
        this.GetInterestInArtCountAsync(null);
    }
    
    /// <remarks/>
    public void GetInterestInArtCountAsync(object userState) {
        if ((this.GetInterestInArtCountOperationCompleted == null)) {
            this.GetInterestInArtCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInterestInArtCountOperationCompleted);
        }
        this.InvokeAsync("GetInterestInArtCount", new object[0], this.GetInterestInArtCountOperationCompleted, userState);
    }
    
    private void OnGetInterestInArtCountOperationCompleted(object arg) {
        if ((this.GetInterestInArtCountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetInterestInArtCountCompleted(this, new GetInterestInArtCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GetInterestInPoliticsCount", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ChartDataPair[] GetInterestInPoliticsCount() {
        object[] results = this.Invoke("GetInterestInPoliticsCount", new object[0]);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetInterestInPoliticsCount(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetInterestInPoliticsCount", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ChartDataPair[] EndGetInterestInPoliticsCount(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public void GetInterestInPoliticsCountAsync() {
        this.GetInterestInPoliticsCountAsync(null);
    }
    
    /// <remarks/>
    public void GetInterestInPoliticsCountAsync(object userState) {
        if ((this.GetInterestInPoliticsCountOperationCompleted == null)) {
            this.GetInterestInPoliticsCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInterestInPoliticsCountOperationCompleted);
        }
        this.InvokeAsync("GetInterestInPoliticsCount", new object[0], this.GetInterestInPoliticsCountOperationCompleted, userState);
    }
    
    private void OnGetInterestInPoliticsCountOperationCompleted(object arg) {
        if ((this.GetInterestInPoliticsCountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetInterestInPoliticsCountCompleted(this, new GetInterestInPoliticsCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GetInterestInLifestyleCount", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ChartDataPair[] GetInterestInLifestyleCount() {
        object[] results = this.Invoke("GetInterestInLifestyleCount", new object[0]);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetInterestInLifestyleCount(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetInterestInLifestyleCount", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ChartDataPair[] EndGetInterestInLifestyleCount(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public void GetInterestInLifestyleCountAsync() {
        this.GetInterestInLifestyleCountAsync(null);
    }
    
    /// <remarks/>
    public void GetInterestInLifestyleCountAsync(object userState) {
        if ((this.GetInterestInLifestyleCountOperationCompleted == null)) {
            this.GetInterestInLifestyleCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInterestInLifestyleCountOperationCompleted);
        }
        this.InvokeAsync("GetInterestInLifestyleCount", new object[0], this.GetInterestInLifestyleCountOperationCompleted, userState);
    }
    
    private void OnGetInterestInLifestyleCountOperationCompleted(object arg) {
        if ((this.GetInterestInLifestyleCountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetInterestInLifestyleCountCompleted(this, new GetInterestInLifestyleCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GetInterestInCareerCount", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ChartDataPair[] GetInterestInCareerCount() {
        object[] results = this.Invoke("GetInterestInCareerCount", new object[0]);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetInterestInCareerCount(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetInterestInCareerCount", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ChartDataPair[] EndGetInterestInCareerCount(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public void GetInterestInCareerCountAsync() {
        this.GetInterestInCareerCountAsync(null);
    }
    
    /// <remarks/>
    public void GetInterestInCareerCountAsync(object userState) {
        if ((this.GetInterestInCareerCountOperationCompleted == null)) {
            this.GetInterestInCareerCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInterestInCareerCountOperationCompleted);
        }
        this.InvokeAsync("GetInterestInCareerCount", new object[0], this.GetInterestInCareerCountOperationCompleted, userState);
    }
    
    private void OnGetInterestInCareerCountOperationCompleted(object arg) {
        if ((this.GetInterestInCareerCountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetInterestInCareerCountCompleted(this, new GetInterestInCareerCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GetUserTagWordCount", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ChartDataPair[] GetUserTagWordCount() {
        object[] results = this.Invoke("GetUserTagWordCount", new object[0]);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetUserTagWordCount(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetUserTagWordCount", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ChartDataPair[] EndGetUserTagWordCount(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public void GetUserTagWordCountAsync() {
        this.GetUserTagWordCountAsync(null);
    }
    
    /// <remarks/>
    public void GetUserTagWordCountAsync(object userState) {
        if ((this.GetUserTagWordCountOperationCompleted == null)) {
            this.GetUserTagWordCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserTagWordCountOperationCompleted);
        }
        this.InvokeAsync("GetUserTagWordCount", new object[0], this.GetUserTagWordCountOperationCompleted, userState);
    }
    
    private void OnGetUserTagWordCountOperationCompleted(object arg) {
        if ((this.GetUserTagWordCountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetUserTagWordCountCompleted(this, new GetUserTagWordCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GetTopEmailProvider", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ChartDataPair[] GetTopEmailProvider() {
        object[] results = this.Invoke("GetTopEmailProvider", new object[0]);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetTopEmailProvider(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetTopEmailProvider", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ChartDataPair[] EndGetTopEmailProvider(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public void GetTopEmailProviderAsync() {
        this.GetTopEmailProviderAsync(null);
    }
    
    /// <remarks/>
    public void GetTopEmailProviderAsync(object userState) {
        if ((this.GetTopEmailProviderOperationCompleted == null)) {
            this.GetTopEmailProviderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopEmailProviderOperationCompleted);
        }
        this.InvokeAsync("GetTopEmailProvider", new object[0], this.GetTopEmailProviderOperationCompleted, userState);
    }
    
    private void OnGetTopEmailProviderOperationCompleted(object arg) {
        if ((this.GetTopEmailProviderCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetTopEmailProviderCompleted(this, new GetTopEmailProviderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GetTopHomeRegion", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ChartDataPair[] GetTopHomeRegion() {
        object[] results = this.Invoke("GetTopHomeRegion", new object[0]);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetTopHomeRegion(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetTopHomeRegion", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public ChartDataPair[] EndGetTopHomeRegion(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ChartDataPair[])(results[0]));
    }
    
    /// <remarks/>
    public void GetTopHomeRegionAsync() {
        this.GetTopHomeRegionAsync(null);
    }
    
    /// <remarks/>
    public void GetTopHomeRegionAsync(object userState) {
        if ((this.GetTopHomeRegionOperationCompleted == null)) {
            this.GetTopHomeRegionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopHomeRegionOperationCompleted);
        }
        this.InvokeAsync("GetTopHomeRegion", new object[0], this.GetTopHomeRegionOperationCompleted, userState);
    }
    
    private void OnGetTopHomeRegionOperationCompleted(object arg) {
        if ((this.GetTopHomeRegionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetTopHomeRegionCompleted(this, new GetTopHomeRegionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://localhost/", IsNullable=false)]
public partial class AuthenticationHeader : System.Web.Services.Protocols.SoapHeader {
    
    private string usernameField;
    
    private string passwordField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public string Username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
public partial class ChartDataPair {
    
    private string idField;
    
    private int valueField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public int Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
public partial class CSBAdWord {
    
    private System.Guid adWordIdField;
    
    private string wordField;
    
    private bool isExactField;
    
    private AdWordFilterActions actionField;
    
    private System.Guid campaignIdField;
    
    private string campaignDescriptionField;
    
    /// <remarks/>
    public System.Guid AdWordId {
        get {
            return this.adWordIdField;
        }
        set {
            this.adWordIdField = value;
        }
    }
    
    /// <remarks/>
    public string Word {
        get {
            return this.wordField;
        }
        set {
            this.wordField = value;
        }
    }
    
    /// <remarks/>
    public bool IsExact {
        get {
            return this.isExactField;
        }
        set {
            this.isExactField = value;
        }
    }
    
    /// <remarks/>
    public AdWordFilterActions Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid CampaignId {
        get {
            return this.campaignIdField;
        }
        set {
            this.campaignIdField = value;
        }
    }
    
    /// <remarks/>
    public string CampaignDescription {
        get {
            return this.campaignDescriptionField;
        }
        set {
            this.campaignDescriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
public enum AdWordFilterActions {
    
    /// <remarks/>
    Link,
    
    /// <remarks/>
    Popup,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
public partial class CSBAdCampaign {
    
    private System.Guid campaignIdField;
    
    private string descriptionField;
    
    private string bannerField;
    
    private string urlField;
    
    private string contentField;
    
    private float creditsField;
    
    private float creditsUsedField;
    
    private float costPerLinkClickField;
    
    private float costPerPopupLinkClickField;
    
    private float costPerBannerClickField;
    
    private float costPerPopupViewField;
    
    private float costPerBannerViewField;
    
    /// <remarks/>
    public System.Guid CampaignId {
        get {
            return this.campaignIdField;
        }
        set {
            this.campaignIdField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Banner {
        get {
            return this.bannerField;
        }
        set {
            this.bannerField = value;
        }
    }
    
    /// <remarks/>
    public string Url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    public string Content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    public float Credits {
        get {
            return this.creditsField;
        }
        set {
            this.creditsField = value;
        }
    }
    
    /// <remarks/>
    public float CreditsUsed {
        get {
            return this.creditsUsedField;
        }
        set {
            this.creditsUsedField = value;
        }
    }
    
    /// <remarks/>
    public float CostPerLinkClick {
        get {
            return this.costPerLinkClickField;
        }
        set {
            this.costPerLinkClickField = value;
        }
    }
    
    /// <remarks/>
    public float CostPerPopupLinkClick {
        get {
            return this.costPerPopupLinkClickField;
        }
        set {
            this.costPerPopupLinkClickField = value;
        }
    }
    
    /// <remarks/>
    public float CostPerBannerClick {
        get {
            return this.costPerBannerClickField;
        }
        set {
            this.costPerBannerClickField = value;
        }
    }
    
    /// <remarks/>
    public float CostPerPopupView {
        get {
            return this.costPerPopupViewField;
        }
        set {
            this.costPerPopupViewField = value;
        }
    }
    
    /// <remarks/>
    public float CostPerBannerView {
        get {
            return this.costPerBannerViewField;
        }
        set {
            this.costPerBannerViewField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
public partial class ContentData {
    
    private string keyField;
    
    private string contentField;
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public string Content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
public partial class CSBDataObject {
    
    private System.Guid objectIdField;
    
    private System.Guid communityIdField;
    
    private System.Guid userIdField;
    
    private ObjectType objectTypeField;
    
    private string titleField;
    
    private string nicknameField;
    
    private bool featuredField;
    
    /// <remarks/>
    public System.Guid ObjectId {
        get {
            return this.objectIdField;
        }
        set {
            this.objectIdField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid CommunityId {
        get {
            return this.communityIdField;
        }
        set {
            this.communityIdField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    public ObjectType ObjectType {
        get {
            return this.objectTypeField;
        }
        set {
            this.objectTypeField = value;
        }
    }
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string Nickname {
        get {
            return this.nicknameField;
        }
        set {
            this.nicknameField = value;
        }
    }
    
    /// <remarks/>
    public bool Featured {
        get {
            return this.featuredField;
        }
        set {
            this.featuredField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
public enum ObjectType {
    
    /// <remarks/>
    Community,
    
    /// <remarks/>
    User,
    
    /// <remarks/>
    Picture,
    
    /// <remarks/>
    Video,
    
    /// <remarks/>
    Tag,
    
    /// <remarks/>
    Audio,
    
    /// <remarks/>
    Article,
    
    /// <remarks/>
    Forum,
    
    /// <remarks/>
    ForumTopic,
    
    /// <remarks/>
    ForumTopicItem,
    
    /// <remarks/>
    SlideShow,
    
    /// <remarks/>
    Folder,
    
    /// <remarks/>
    Event,
    
    /// <remarks/>
    News,
    
    /// <remarks/>
    PinboardSearch,
    
    /// <remarks/>
    PinboardOffer,
    
    /// <remarks/>
    ProfileCommunity,
    
    /// <remarks/>
    LinkedVideo,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
public partial class User {
    
    private string usernameField;
    
    private string emailField;
    
    private string fullnameField;
    
    private System.DateTime lastLoginDateField;
    
    private System.DateTime lastLockoutDateField;
    
    private bool isLockedField;
    
    /// <remarks/>
    public string Username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public string Fullname {
        get {
            return this.fullnameField;
        }
        set {
            this.fullnameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime LastLoginDate {
        get {
            return this.lastLoginDateField;
        }
        set {
            this.lastLoginDateField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime LastLockoutDate {
        get {
            return this.lastLockoutDateField;
        }
        set {
            this.lastLockoutDateField = value;
        }
    }
    
    /// <remarks/>
    public bool IsLocked {
        get {
            return this.isLockedField;
        }
        set {
            this.isLockedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
public partial class Authorization {
    
    private string versionField;
    
    private bool isAuthorizedField;
    
    private Role[] rolesField;
    
    /// <remarks/>
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    public bool IsAuthorized {
        get {
            return this.isAuthorizedField;
        }
        set {
            this.isAuthorizedField = value;
        }
    }
    
    /// <remarks/>
    public Role[] Roles {
        get {
            return this.rolesField;
        }
        set {
            this.rolesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
public enum Role {
    
    /// <remarks/>
    StatisticsViewer,
    
    /// <remarks/>
    UserManager,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void AuthenticateCompletedEventHandler(object sender, AuthenticateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Authorization Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Authorization)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetUsersCompletedEventHandler(object sender, GetUsersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public User[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((User[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void LockUserCompletedEventHandler(object sender, LockUserCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LockUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LockUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void UnlockUserCompletedEventHandler(object sender, UnlockUserCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UnlockUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UnlockUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void SetUserEmailCompletedEventHandler(object sender, SetUserEmailCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SetUserEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SetUserEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetDataObjectsCompletedEventHandler(object sender, GetDataObjectsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDataObjectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDataObjectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CSBDataObject[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CSBDataObject[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void FeatureDataObjectCompletedEventHandler(object sender, FeatureDataObjectCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class FeatureDataObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal FeatureDataObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetContentDataCompletedEventHandler(object sender, GetContentDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetContentDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetContentDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ContentData[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ContentData[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void SetContentDataCompletedEventHandler(object sender, SetContentDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SetContentDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SetContentDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetAdCampaignsCompletedEventHandler(object sender, GetAdCampaignsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetAdCampaignsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetAdCampaignsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CSBAdCampaign[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CSBAdCampaign[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void SaveAdCampaignCompletedEventHandler(object sender, SaveAdCampaignCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SaveAdCampaignCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SaveAdCampaignCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetAdWordsCompletedEventHandler(object sender, GetAdWordsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetAdWordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetAdWordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public CSBAdWord[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((CSBAdWord[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void SaveAdWordCompletedEventHandler(object sender, SaveAdWordCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SaveAdWordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SaveAdWordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetObjectCountPerTypeCompletedEventHandler(object sender, GetObjectCountPerTypeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetObjectCountPerTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetObjectCountPerTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ChartDataPair[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ChartDataPair[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetObjectCountPerTypeTodayCompletedEventHandler(object sender, GetObjectCountPerTypeTodayCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetObjectCountPerTypeTodayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetObjectCountPerTypeTodayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ChartDataPair[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ChartDataPair[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetObjectViewCountPerTypeCompletedEventHandler(object sender, GetObjectViewCountPerTypeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetObjectViewCountPerTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetObjectViewCountPerTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ChartDataPair[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ChartDataPair[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetObjectViewCountPerTypeTodayCompletedEventHandler(object sender, GetObjectViewCountPerTypeTodayCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetObjectViewCountPerTypeTodayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetObjectViewCountPerTypeTodayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ChartDataPair[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ChartDataPair[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetInterestInArtCountCompletedEventHandler(object sender, GetInterestInArtCountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetInterestInArtCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetInterestInArtCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ChartDataPair[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ChartDataPair[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetInterestInPoliticsCountCompletedEventHandler(object sender, GetInterestInPoliticsCountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetInterestInPoliticsCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetInterestInPoliticsCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ChartDataPair[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ChartDataPair[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetInterestInLifestyleCountCompletedEventHandler(object sender, GetInterestInLifestyleCountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetInterestInLifestyleCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetInterestInLifestyleCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ChartDataPair[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ChartDataPair[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetInterestInCareerCountCompletedEventHandler(object sender, GetInterestInCareerCountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetInterestInCareerCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetInterestInCareerCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ChartDataPair[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ChartDataPair[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetUserTagWordCountCompletedEventHandler(object sender, GetUserTagWordCountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetUserTagWordCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetUserTagWordCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ChartDataPair[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ChartDataPair[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetTopEmailProviderCompletedEventHandler(object sender, GetTopEmailProviderCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetTopEmailProviderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetTopEmailProviderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ChartDataPair[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ChartDataPair[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void GetTopHomeRegionCompletedEventHandler(object sender, GetTopHomeRegionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetTopHomeRegionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetTopHomeRegionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ChartDataPair[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ChartDataPair[])(this.results[0]));
        }
    }
}
