#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4screen.CSB.DataObj.Business
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="CSBooster.3.0.0.0")]
	public partial class ShopDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserthitbl_ShoppingCart_Cart_SHO(hitbl_ShoppingCart_Cart_SHO instance);
    partial void Updatehitbl_ShoppingCart_Cart_SHO(hitbl_ShoppingCart_Cart_SHO instance);
    partial void Deletehitbl_ShoppingCart_Cart_SHO(hitbl_ShoppingCart_Cart_SHO instance);
    partial void Inserthitbl_ShoppingCart_Items_ITE(hitbl_ShoppingCart_Items_ITE instance);
    partial void Updatehitbl_ShoppingCart_Items_ITE(hitbl_ShoppingCart_Items_ITE instance);
    partial void Deletehitbl_ShoppingCart_Items_ITE(hitbl_ShoppingCart_Items_ITE instance);
    #endregion
		
		public ShopDataContext() : 
				base("Data Source=4SAPPL02\\SQL2005;Initial Catalog=CSBooster.3.0.0.0;User ID=CSBooster_" +
						"User", mappingSource)
		{
			OnCreated();
		}
		
		public ShopDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShopDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShopDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShopDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<hitbl_ShoppingCart_Cart_SHO> hitbl_ShoppingCart_Cart_SHOs
		{
			get
			{
				return this.GetTable<hitbl_ShoppingCart_Cart_SHO>();
			}
		}
		
		public System.Data.Linq.Table<hitbl_ShoppingCart_Items_ITE> hitbl_ShoppingCart_Items_ITEs
		{
			get
			{
				return this.GetTable<hitbl_ShoppingCart_Items_ITE>();
			}
		}
	}
	
	[Table(Name="dbo.hitbl_ShoppingCart_Cart_SHO")]
	public partial class hitbl_ShoppingCart_Cart_SHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _SHO_CARTID;
		
		private System.Guid _SHO_USERID;
		
		private int _SHO_CARTSTATUS;
		
		private string _SHO_NAME;
		
		private string _SHO_LASTNAME;
		
		private string _SHO_FIRM;
		
		private string _SHO_ADDRESS1;
		
		private string _SHO_ADDRESS2;
		
		private string _SHO_PLZ;
		
		private string _SHO_CITY;
		
		private string _SHO_TEL;
		
		private string _SHO_EMAIL;
		
		private System.DateTime _SHO_DATEADDED;
		
		private System.Nullable<double> _SHO_TAXES;
		
		private System.Nullable<double> _SHO_TRANSPORT;
		
		private string _SHO_ANREDE;
		
		private string _SHO_COMMENT;
		
		private EntitySet<hitbl_ShoppingCart_Items_ITE> _hitbl_ShoppingCart_Items_ITEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSHO_CARTIDChanging(System.Guid value);
    partial void OnSHO_CARTIDChanged();
    partial void OnSHO_USERIDChanging(System.Guid value);
    partial void OnSHO_USERIDChanged();
    partial void OnSHO_CARTSTATUSChanging(int value);
    partial void OnSHO_CARTSTATUSChanged();
    partial void OnSHO_NAMEChanging(string value);
    partial void OnSHO_NAMEChanged();
    partial void OnSHO_LASTNAMEChanging(string value);
    partial void OnSHO_LASTNAMEChanged();
    partial void OnSHO_FIRMChanging(string value);
    partial void OnSHO_FIRMChanged();
    partial void OnSHO_ADDRESS1Changing(string value);
    partial void OnSHO_ADDRESS1Changed();
    partial void OnSHO_ADDRESS2Changing(string value);
    partial void OnSHO_ADDRESS2Changed();
    partial void OnSHO_PLZChanging(string value);
    partial void OnSHO_PLZChanged();
    partial void OnSHO_CITYChanging(string value);
    partial void OnSHO_CITYChanged();
    partial void OnSHO_TELChanging(string value);
    partial void OnSHO_TELChanged();
    partial void OnSHO_EMAILChanging(string value);
    partial void OnSHO_EMAILChanged();
    partial void OnSHO_DATEADDEDChanging(System.DateTime value);
    partial void OnSHO_DATEADDEDChanged();
    partial void OnSHO_TAXESChanging(System.Nullable<double> value);
    partial void OnSHO_TAXESChanged();
    partial void OnSHO_TRANSPORTChanging(System.Nullable<double> value);
    partial void OnSHO_TRANSPORTChanged();
    partial void OnSHO_ANREDEChanging(string value);
    partial void OnSHO_ANREDEChanged();
    partial void OnSHO_COMMENTChanging(string value);
    partial void OnSHO_COMMENTChanged();
    #endregion
		
		public hitbl_ShoppingCart_Cart_SHO()
		{
			this._hitbl_ShoppingCart_Items_ITEs = new EntitySet<hitbl_ShoppingCart_Items_ITE>(new Action<hitbl_ShoppingCart_Items_ITE>(this.attach_hitbl_ShoppingCart_Items_ITEs), new Action<hitbl_ShoppingCart_Items_ITE>(this.detach_hitbl_ShoppingCart_Items_ITEs));
			OnCreated();
		}
		
		[Column(Storage="_SHO_CARTID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid SHO_CARTID
		{
			get
			{
				return this._SHO_CARTID;
			}
			set
			{
				if ((this._SHO_CARTID != value))
				{
					this.OnSHO_CARTIDChanging(value);
					this.SendPropertyChanging();
					this._SHO_CARTID = value;
					this.SendPropertyChanged("SHO_CARTID");
					this.OnSHO_CARTIDChanged();
				}
			}
		}
		
		[Column(Storage="_SHO_USERID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SHO_USERID
		{
			get
			{
				return this._SHO_USERID;
			}
			set
			{
				if ((this._SHO_USERID != value))
				{
					this.OnSHO_USERIDChanging(value);
					this.SendPropertyChanging();
					this._SHO_USERID = value;
					this.SendPropertyChanged("SHO_USERID");
					this.OnSHO_USERIDChanged();
				}
			}
		}
		
		[Column(Storage="_SHO_CARTSTATUS", DbType="Int NOT NULL")]
		public int SHO_CARTSTATUS
		{
			get
			{
				return this._SHO_CARTSTATUS;
			}
			set
			{
				if ((this._SHO_CARTSTATUS != value))
				{
					this.OnSHO_CARTSTATUSChanging(value);
					this.SendPropertyChanging();
					this._SHO_CARTSTATUS = value;
					this.SendPropertyChanged("SHO_CARTSTATUS");
					this.OnSHO_CARTSTATUSChanged();
				}
			}
		}
		
		[Column(Storage="_SHO_NAME", DbType="NVarChar(50)")]
		public string SHO_NAME
		{
			get
			{
				return this._SHO_NAME;
			}
			set
			{
				if ((this._SHO_NAME != value))
				{
					this.OnSHO_NAMEChanging(value);
					this.SendPropertyChanging();
					this._SHO_NAME = value;
					this.SendPropertyChanged("SHO_NAME");
					this.OnSHO_NAMEChanged();
				}
			}
		}
		
		[Column(Storage="_SHO_LASTNAME", DbType="NVarChar(50)")]
		public string SHO_LASTNAME
		{
			get
			{
				return this._SHO_LASTNAME;
			}
			set
			{
				if ((this._SHO_LASTNAME != value))
				{
					this.OnSHO_LASTNAMEChanging(value);
					this.SendPropertyChanging();
					this._SHO_LASTNAME = value;
					this.SendPropertyChanged("SHO_LASTNAME");
					this.OnSHO_LASTNAMEChanged();
				}
			}
		}
		
		[Column(Storage="_SHO_FIRM", DbType="NVarChar(50)")]
		public string SHO_FIRM
		{
			get
			{
				return this._SHO_FIRM;
			}
			set
			{
				if ((this._SHO_FIRM != value))
				{
					this.OnSHO_FIRMChanging(value);
					this.SendPropertyChanging();
					this._SHO_FIRM = value;
					this.SendPropertyChanged("SHO_FIRM");
					this.OnSHO_FIRMChanged();
				}
			}
		}
		
		[Column(Storage="_SHO_ADDRESS1", DbType="NVarChar(300)")]
		public string SHO_ADDRESS1
		{
			get
			{
				return this._SHO_ADDRESS1;
			}
			set
			{
				if ((this._SHO_ADDRESS1 != value))
				{
					this.OnSHO_ADDRESS1Changing(value);
					this.SendPropertyChanging();
					this._SHO_ADDRESS1 = value;
					this.SendPropertyChanged("SHO_ADDRESS1");
					this.OnSHO_ADDRESS1Changed();
				}
			}
		}
		
		[Column(Storage="_SHO_ADDRESS2", DbType="NVarChar(300)")]
		public string SHO_ADDRESS2
		{
			get
			{
				return this._SHO_ADDRESS2;
			}
			set
			{
				if ((this._SHO_ADDRESS2 != value))
				{
					this.OnSHO_ADDRESS2Changing(value);
					this.SendPropertyChanging();
					this._SHO_ADDRESS2 = value;
					this.SendPropertyChanged("SHO_ADDRESS2");
					this.OnSHO_ADDRESS2Changed();
				}
			}
		}
		
		[Column(Storage="_SHO_PLZ", DbType="NVarChar(10)")]
		public string SHO_PLZ
		{
			get
			{
				return this._SHO_PLZ;
			}
			set
			{
				if ((this._SHO_PLZ != value))
				{
					this.OnSHO_PLZChanging(value);
					this.SendPropertyChanging();
					this._SHO_PLZ = value;
					this.SendPropertyChanged("SHO_PLZ");
					this.OnSHO_PLZChanged();
				}
			}
		}
		
		[Column(Storage="_SHO_CITY", DbType="NVarChar(50)")]
		public string SHO_CITY
		{
			get
			{
				return this._SHO_CITY;
			}
			set
			{
				if ((this._SHO_CITY != value))
				{
					this.OnSHO_CITYChanging(value);
					this.SendPropertyChanging();
					this._SHO_CITY = value;
					this.SendPropertyChanged("SHO_CITY");
					this.OnSHO_CITYChanged();
				}
			}
		}
		
		[Column(Storage="_SHO_TEL", DbType="NVarChar(50)")]
		public string SHO_TEL
		{
			get
			{
				return this._SHO_TEL;
			}
			set
			{
				if ((this._SHO_TEL != value))
				{
					this.OnSHO_TELChanging(value);
					this.SendPropertyChanging();
					this._SHO_TEL = value;
					this.SendPropertyChanged("SHO_TEL");
					this.OnSHO_TELChanged();
				}
			}
		}
		
		[Column(Storage="_SHO_EMAIL", DbType="NVarChar(80)")]
		public string SHO_EMAIL
		{
			get
			{
				return this._SHO_EMAIL;
			}
			set
			{
				if ((this._SHO_EMAIL != value))
				{
					this.OnSHO_EMAILChanging(value);
					this.SendPropertyChanging();
					this._SHO_EMAIL = value;
					this.SendPropertyChanged("SHO_EMAIL");
					this.OnSHO_EMAILChanged();
				}
			}
		}
		
		[Column(Storage="_SHO_DATEADDED", DbType="DateTime NOT NULL")]
		public System.DateTime SHO_DATEADDED
		{
			get
			{
				return this._SHO_DATEADDED;
			}
			set
			{
				if ((this._SHO_DATEADDED != value))
				{
					this.OnSHO_DATEADDEDChanging(value);
					this.SendPropertyChanging();
					this._SHO_DATEADDED = value;
					this.SendPropertyChanged("SHO_DATEADDED");
					this.OnSHO_DATEADDEDChanged();
				}
			}
		}
		
		[Column(Storage="_SHO_TAXES", DbType="Float")]
		public System.Nullable<double> SHO_TAXES
		{
			get
			{
				return this._SHO_TAXES;
			}
			set
			{
				if ((this._SHO_TAXES != value))
				{
					this.OnSHO_TAXESChanging(value);
					this.SendPropertyChanging();
					this._SHO_TAXES = value;
					this.SendPropertyChanged("SHO_TAXES");
					this.OnSHO_TAXESChanged();
				}
			}
		}
		
		[Column(Storage="_SHO_TRANSPORT", DbType="Float")]
		public System.Nullable<double> SHO_TRANSPORT
		{
			get
			{
				return this._SHO_TRANSPORT;
			}
			set
			{
				if ((this._SHO_TRANSPORT != value))
				{
					this.OnSHO_TRANSPORTChanging(value);
					this.SendPropertyChanging();
					this._SHO_TRANSPORT = value;
					this.SendPropertyChanged("SHO_TRANSPORT");
					this.OnSHO_TRANSPORTChanged();
				}
			}
		}
		
		[Column(Storage="_SHO_ANREDE", DbType="NVarChar(10)")]
		public string SHO_ANREDE
		{
			get
			{
				return this._SHO_ANREDE;
			}
			set
			{
				if ((this._SHO_ANREDE != value))
				{
					this.OnSHO_ANREDEChanging(value);
					this.SendPropertyChanging();
					this._SHO_ANREDE = value;
					this.SendPropertyChanged("SHO_ANREDE");
					this.OnSHO_ANREDEChanged();
				}
			}
		}
		
		[Column(Storage="_SHO_COMMENT", DbType="NVarChar(MAX)")]
		public string SHO_COMMENT
		{
			get
			{
				return this._SHO_COMMENT;
			}
			set
			{
				if ((this._SHO_COMMENT != value))
				{
					this.OnSHO_COMMENTChanging(value);
					this.SendPropertyChanging();
					this._SHO_COMMENT = value;
					this.SendPropertyChanged("SHO_COMMENT");
					this.OnSHO_COMMENTChanged();
				}
			}
		}
		
		[Association(Name="hitbl_ShoppingCart_Cart_SHO_hitbl_ShoppingCart_Items_ITE", Storage="_hitbl_ShoppingCart_Items_ITEs", ThisKey="SHO_CARTID", OtherKey="SHO_CARTID")]
		public EntitySet<hitbl_ShoppingCart_Items_ITE> hitbl_ShoppingCart_Items_ITEs
		{
			get
			{
				return this._hitbl_ShoppingCart_Items_ITEs;
			}
			set
			{
				this._hitbl_ShoppingCart_Items_ITEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hitbl_ShoppingCart_Items_ITEs(hitbl_ShoppingCart_Items_ITE entity)
		{
			this.SendPropertyChanging();
			entity.hitbl_ShoppingCart_Cart_SHO = this;
		}
		
		private void detach_hitbl_ShoppingCart_Items_ITEs(hitbl_ShoppingCart_Items_ITE entity)
		{
			this.SendPropertyChanging();
			entity.hitbl_ShoppingCart_Cart_SHO = null;
		}
	}
	
	[Table(Name="dbo.hitbl_ShoppingCart_Items_ITE")]
	public partial class hitbl_ShoppingCart_Items_ITE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ITE_ITEM_ID;
		
		private System.Guid _SHO_CARTID;
		
		private int _ITE_QUANTITY;
		
		private string _ITE_REFNR;
		
		private string _ITE_TITEL;
		
		private string _ITE_TEXT;
		
		private System.Nullable<double> _ITE_PRICE1;
		
		private System.Nullable<double> _ITE_PRICE2;
		
		private System.Nullable<double> _ITE_PRICE3;
		
		private System.Nullable<double> _ITE_Porto;
		
		private System.Guid _OBJ_ID;
		
		private string _ITE_COMENT;
		
		private EntityRef<hitbl_ShoppingCart_Cart_SHO> _hitbl_ShoppingCart_Cart_SHO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnITE_ITEM_IDChanging(System.Guid value);
    partial void OnITE_ITEM_IDChanged();
    partial void OnSHO_CARTIDChanging(System.Guid value);
    partial void OnSHO_CARTIDChanged();
    partial void OnITE_QUANTITYChanging(int value);
    partial void OnITE_QUANTITYChanged();
    partial void OnITE_REFNRChanging(string value);
    partial void OnITE_REFNRChanged();
    partial void OnITE_TITELChanging(string value);
    partial void OnITE_TITELChanged();
    partial void OnITE_TEXTChanging(string value);
    partial void OnITE_TEXTChanged();
    partial void OnITE_PRICE1Changing(System.Nullable<double> value);
    partial void OnITE_PRICE1Changed();
    partial void OnITE_PRICE2Changing(System.Nullable<double> value);
    partial void OnITE_PRICE2Changed();
    partial void OnITE_PRICE3Changing(System.Nullable<double> value);
    partial void OnITE_PRICE3Changed();
    partial void OnITE_PortoChanging(System.Nullable<double> value);
    partial void OnITE_PortoChanged();
    partial void OnOBJ_IDChanging(System.Guid value);
    partial void OnOBJ_IDChanged();
    partial void OnITE_COMENTChanging(string value);
    partial void OnITE_COMENTChanged();
    #endregion
		
		public hitbl_ShoppingCart_Items_ITE()
		{
			this._hitbl_ShoppingCart_Cart_SHO = default(EntityRef<hitbl_ShoppingCart_Cart_SHO>);
			OnCreated();
		}
		
		[Column(Storage="_ITE_ITEM_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ITE_ITEM_ID
		{
			get
			{
				return this._ITE_ITEM_ID;
			}
			set
			{
				if ((this._ITE_ITEM_ID != value))
				{
					this.OnITE_ITEM_IDChanging(value);
					this.SendPropertyChanging();
					this._ITE_ITEM_ID = value;
					this.SendPropertyChanged("ITE_ITEM_ID");
					this.OnITE_ITEM_IDChanged();
				}
			}
		}
		
		[Column(Storage="_SHO_CARTID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SHO_CARTID
		{
			get
			{
				return this._SHO_CARTID;
			}
			set
			{
				if ((this._SHO_CARTID != value))
				{
					if (this._hitbl_ShoppingCart_Cart_SHO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSHO_CARTIDChanging(value);
					this.SendPropertyChanging();
					this._SHO_CARTID = value;
					this.SendPropertyChanged("SHO_CARTID");
					this.OnSHO_CARTIDChanged();
				}
			}
		}
		
		[Column(Storage="_ITE_QUANTITY", DbType="Int NOT NULL")]
		public int ITE_QUANTITY
		{
			get
			{
				return this._ITE_QUANTITY;
			}
			set
			{
				if ((this._ITE_QUANTITY != value))
				{
					this.OnITE_QUANTITYChanging(value);
					this.SendPropertyChanging();
					this._ITE_QUANTITY = value;
					this.SendPropertyChanged("ITE_QUANTITY");
					this.OnITE_QUANTITYChanged();
				}
			}
		}
		
		[Column(Storage="_ITE_REFNR", DbType="NVarChar(50)")]
		public string ITE_REFNR
		{
			get
			{
				return this._ITE_REFNR;
			}
			set
			{
				if ((this._ITE_REFNR != value))
				{
					this.OnITE_REFNRChanging(value);
					this.SendPropertyChanging();
					this._ITE_REFNR = value;
					this.SendPropertyChanged("ITE_REFNR");
					this.OnITE_REFNRChanged();
				}
			}
		}
		
		[Column(Storage="_ITE_TITEL", DbType="NVarChar(100)")]
		public string ITE_TITEL
		{
			get
			{
				return this._ITE_TITEL;
			}
			set
			{
				if ((this._ITE_TITEL != value))
				{
					this.OnITE_TITELChanging(value);
					this.SendPropertyChanging();
					this._ITE_TITEL = value;
					this.SendPropertyChanged("ITE_TITEL");
					this.OnITE_TITELChanged();
				}
			}
		}
		
		[Column(Storage="_ITE_TEXT", DbType="NVarChar(MAX)")]
		public string ITE_TEXT
		{
			get
			{
				return this._ITE_TEXT;
			}
			set
			{
				if ((this._ITE_TEXT != value))
				{
					this.OnITE_TEXTChanging(value);
					this.SendPropertyChanging();
					this._ITE_TEXT = value;
					this.SendPropertyChanged("ITE_TEXT");
					this.OnITE_TEXTChanged();
				}
			}
		}
		
		[Column(Storage="_ITE_PRICE1", DbType="Float")]
		public System.Nullable<double> ITE_PRICE1
		{
			get
			{
				return this._ITE_PRICE1;
			}
			set
			{
				if ((this._ITE_PRICE1 != value))
				{
					this.OnITE_PRICE1Changing(value);
					this.SendPropertyChanging();
					this._ITE_PRICE1 = value;
					this.SendPropertyChanged("ITE_PRICE1");
					this.OnITE_PRICE1Changed();
				}
			}
		}
		
		[Column(Storage="_ITE_PRICE2", DbType="Float")]
		public System.Nullable<double> ITE_PRICE2
		{
			get
			{
				return this._ITE_PRICE2;
			}
			set
			{
				if ((this._ITE_PRICE2 != value))
				{
					this.OnITE_PRICE2Changing(value);
					this.SendPropertyChanging();
					this._ITE_PRICE2 = value;
					this.SendPropertyChanged("ITE_PRICE2");
					this.OnITE_PRICE2Changed();
				}
			}
		}
		
		[Column(Storage="_ITE_PRICE3", DbType="Float")]
		public System.Nullable<double> ITE_PRICE3
		{
			get
			{
				return this._ITE_PRICE3;
			}
			set
			{
				if ((this._ITE_PRICE3 != value))
				{
					this.OnITE_PRICE3Changing(value);
					this.SendPropertyChanging();
					this._ITE_PRICE3 = value;
					this.SendPropertyChanged("ITE_PRICE3");
					this.OnITE_PRICE3Changed();
				}
			}
		}
		
		[Column(Storage="_ITE_Porto", DbType="Float")]
		public System.Nullable<double> ITE_Porto
		{
			get
			{
				return this._ITE_Porto;
			}
			set
			{
				if ((this._ITE_Porto != value))
				{
					this.OnITE_PortoChanging(value);
					this.SendPropertyChanging();
					this._ITE_Porto = value;
					this.SendPropertyChanged("ITE_Porto");
					this.OnITE_PortoChanged();
				}
			}
		}
		
		[Column(Storage="_OBJ_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid OBJ_ID
		{
			get
			{
				return this._OBJ_ID;
			}
			set
			{
				if ((this._OBJ_ID != value))
				{
					this.OnOBJ_IDChanging(value);
					this.SendPropertyChanging();
					this._OBJ_ID = value;
					this.SendPropertyChanged("OBJ_ID");
					this.OnOBJ_IDChanged();
				}
			}
		}
		
		[Column(Storage="_ITE_COMENT", DbType="NVarChar(256)")]
		public string ITE_COMENT
		{
			get
			{
				return this._ITE_COMENT;
			}
			set
			{
				if ((this._ITE_COMENT != value))
				{
					this.OnITE_COMENTChanging(value);
					this.SendPropertyChanging();
					this._ITE_COMENT = value;
					this.SendPropertyChanged("ITE_COMENT");
					this.OnITE_COMENTChanged();
				}
			}
		}
		
		[Association(Name="hitbl_ShoppingCart_Cart_SHO_hitbl_ShoppingCart_Items_ITE", Storage="_hitbl_ShoppingCart_Cart_SHO", ThisKey="SHO_CARTID", OtherKey="SHO_CARTID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public hitbl_ShoppingCart_Cart_SHO hitbl_ShoppingCart_Cart_SHO
		{
			get
			{
				return this._hitbl_ShoppingCart_Cart_SHO.Entity;
			}
			set
			{
				hitbl_ShoppingCart_Cart_SHO previousValue = this._hitbl_ShoppingCart_Cart_SHO.Entity;
				if (((previousValue != value) 
							|| (this._hitbl_ShoppingCart_Cart_SHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hitbl_ShoppingCart_Cart_SHO.Entity = null;
						previousValue.hitbl_ShoppingCart_Items_ITEs.Remove(this);
					}
					this._hitbl_ShoppingCart_Cart_SHO.Entity = value;
					if ((value != null))
					{
						value.hitbl_ShoppingCart_Items_ITEs.Add(this);
						this._SHO_CARTID = value.SHO_CARTID;
					}
					else
					{
						this._SHO_CARTID = default(System.Guid);
					}
					this.SendPropertyChanged("hitbl_ShoppingCart_Cart_SHO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
